GET http://localhost:3000/ping


###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"Nikhil",
    "email":"nikkssy.dev@gmail.com",
    "password":"Gasmonkey@123"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"nikkssy.dev@gmail.com",
    "password":"Gasmonkey@123"
}


###
POST http://localhost:3000/api/note
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibmlra3NzeS5kZXZAZ21haWwuY29tIiwiaWF0IjoxNzgxNDQyNTMxLCJleHAiOjE3ODE1Mjg5MzF9.aF-vkZTKx9Du4u_xsoDfo5r_RAaFFvMmnxQxVEe474c

{
    "title":"nikkssy.dev@gmail.com"
}